### ISSUE TITLE
file://cdn.webix.com/extras/pdfjs.js - failed to load resource

### ISSUE THREAD

**Issue by icetafax** [webix-hub/cdn-extras#1]
Error when trying to use webix.toPDF() function.
github.com/rkusa/pdfjs is not a mozilla.github.io/pdf.js/ 
Documentation (http://docs.webix.com/datatable__exporttopdf.html) redirects to the second project - at the bottom before comment section is written "More possible configuration properties are described in the corresponding documentation (follow the "document/tableopts" section").

**Comment by mkozhukh** [comment]
Please run a sample through some kind of web-server.
Using Webix UI directly from file-system ( by file:// protocol ) is not supported.

http://webix.com/snippet/6b4f7220

> github.com/rkusa/pdfjs is not a mozilla.github.io/pdf.js/ 
> Yes, there are two libs named pdfjs, one is PDFJs from mozilla, used to show pdf files in a browser. Second is pdfjs from rkusa, which is used to generate pdf files.
